### ISSUE TITLE
bot does not work

### ISSUE THREAD

**Issue by arxisox** [felixsam359/Discord-Weather#2]
Hello, the bot does not work, it deletes the message we are sending and does not write anything
![Screenshot 2021-08-22 153612](https://user-images.githubusercontent.com/61984673/130352873-4922c936-2fe1-4b55-b5d2-532bb28cef12.png)

**Comment by felixsam359** [comment]
So let's troubleshoot
- Does the bot has enough permission to send messages in that channel? Try to give the bot administrater permission and test again.
- Did you turned on privileged gateway intents on in Discord Developers Portal?
- You can come and test the bot here
https://discord.gg/wFennGqr

**Comment by felixsam359** [comment]
**Solved ✅**
[Transcript](https://wwnafzwj1ez0uycupublnw-on.drv.tw/Issues/issue%232.html)
